### ISSUE TITLE
use of ConfigureResourceProvider leads to exception

### ISSUE THREAD

**Issue by petroniuchacz** [RusKnyaz/Optimus#33]
Hi, I am trying to use the ConfigureResourceProvider to modify the request header. I'm getting 
this exception. It fails also with empty action bodies in the method. I'm using .NET Core 3.

```
       async static Task<string> GetPage(string url)
        {
            var engine = EngineBuilder.New()
                .ConfigureResourceProvider(x => x.Notify(
                    request => {},
                    response => { /*handle response */}))
                .UseJint()
                .Build();

            var page = await engine.OpenUrl(url);
            
            var document = page.Document;
            
            string content = document.Body.OuterHTML;
            return content;
        }
```

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Knyaz.Optimus
  StackTrace:
   at Knyaz.Optimus.ResourceProviders.ResourceProvider.SendRequestAsync(Request req)
   at Knyaz.Optimus.ResourceProviders.NotifyingResourceProvider.SendRequestAsync(Request request)
   at Knyaz.Optimus.ResourceProviders.NotifyingResourceProvider.SendRequestAsync(Request request)
   at Knyaz.Optimus.Engine.<OpenUrl>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Knyaz.Optimus.Engine.<OpenUrl>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DevLab.Program.<GetPage>d__10.MoveNext() in C:\Users\DGT638\source\repos\RelatedWords\DevLab\Program.cs:line 226
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at DevLab.Program.<Main>d__6.MoveNext() in C:\Users\DGT638\source\repos\RelatedWords\DevLab\Program.cs:line 156
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DevLab.Program.<Main>(String[] args)
```

**Comment by RusKnyaz** [comment]
It is due to the http resource provider has not been configured. You should replace **x.Notify** with **x.Http().Notify**
